changelog:
  exclude:
    authors:
      - github-actions
      - github-actions[bot]
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Fixes
      labels:
        - bug
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🧪 Tests & CI
      labels:
        - test
        - ci
    - title: 🔧 Other Changes
      labels:
        - "*"
