apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: noctaya
    app.kubernetes.io/managed-by: kustomize
  name: llmservice-admin-role
rules:
- apiGroups:
  - serving.noctaya.io
  resources:
  - llmservices
  verbs:
  - '*'
- apiGroups:
  - serving.noctaya.io
  resources:
  - llmservices/status
  verbs:
  - get
