resources:
- bases/serving.noctaya.io_inferenceruntimes.yaml
- bases/serving.noctaya.io_llmservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# +kubebuilder:scaffold:crdkustomizewebhookpatch

#configurations:
#- kustomizeconfig.yaml
